In [39]:
import numpy as np
from numpy import pi

In [2]:
a = np.arange(15).reshape(3, 5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.ndim

2

In [7]:
a.dtype.name

'int64'

In [8]:
a.itemsize



8

In [9]:
a.size

15

In [10]:
type(a)

numpy.ndarray

In [14]:
b = np.array([6,7,8])

In [15]:
b

array([6, 7, 8])

In [16]:
type(b)

numpy.ndarray

In [17]:
c = np.array([1,23,4 ])

In [18]:
c

array([ 1, 23,  4])

In [19]:
c.dtype

dtype('int64')

In [22]:
d = np.array([(1.5, 2.5, 3.6), (4,5,6)])

In [23]:
d.dtype

dtype('float64')

In [24]:
d

array([[1.5, 2.5, 3.6],
       [4. , 5. , 6. ]])

In [25]:
b.size()

TypeError: 'int' object is not callable

In [27]:
d.size

6

In [28]:
d.shape

(2, 3)

In [29]:
d.itemsize

8

In [30]:
d.ndim

2

In [32]:
c = np.array([ [1,2], [3,4] ], dtype=complex)

In [33]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [34]:
c.shape

(2, 2)

In [35]:
c.dtype

dtype('complex128')

In [36]:
c.ndim

2

In [37]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [38]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [42]:
np.arange(15).reshape(5, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [43]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [46]:
np.arange(24).reshape(8,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [47]:
print(np.arange(24).reshape(8,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [48]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [49]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [50]:
a = np.array([25, 23, 19, 14])

In [51]:
b = np.arange(4)

In [53]:
b

array([0, 1, 2, 3])

In [54]:
a -b

array([25, 22, 17, 11])

In [55]:
b **2

array([0, 1, 4, 9])

In [56]:
10 * np.sin(a)

array([-1.3235175 , -8.46220404,  1.4987721 ,  9.90607356])

In [57]:
a < 35

array([ True,  True,  True,  True])

In [58]:
a = np.array([[1,1] , [0,1]])

In [59]:
b = np.array([[2, 0], [3,4]])

In [60]:
a * b

array([[2, 0],
       [0, 4]])

In [62]:
a.dot(b)

array([[5, 4],
       [3, 4]])

In [63]:
a @ b

array([[5, 4],
       [3, 4]])

In [64]:
rg = np.random.default_rng(1)
a = np.ones((2,3), dtype=int)


In [71]:
b =rg.random((2,3))

In [67]:
a *= 3

In [72]:
b

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [73]:
b += a

In [74]:
b

array([[3.82770259, 3.40919914, 3.54959369],
       [3.02755911, 3.75351311, 3.53814331]])

In [75]:
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [77]:
a = rg.random((2, 3))

In [78]:
a

array([[0.32973172, 0.7884287 , 0.30319483],
       [0.45349789, 0.1340417 , 0.40311299]])

In [79]:
a.sum()

2.412007822394087

In [80]:
a.min()

0.13404169724716475

In [81]:
a.max()

0.7884287034284043

In [82]:
b = np.arange(12).reshape(3, 4)

In [84]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [85]:
b.min(axis=1)

array([0, 4, 8])

In [86]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])